// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnsdma7ZbbPRwtrPxHTSAteDQTPvF8gQc',
    appId: '1:829048536709:web:616645921e6f9f7c9833ec',
    messagingSenderId: '829048536709',
    projectId: 'chat-app-49d7a',
    authDomain: 'chat-app-49d7a.firebaseapp.com',
    storageBucket: 'chat-app-49d7a.firebasestorage.app',
    measurementId: 'G-ECM9DTJXT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB48GMBnvK9ADdEJmbpc1oVtRNLNEVCZi0',
    appId: '1:829048536709:android:76cb315045c045c69833ec',
    messagingSenderId: '829048536709',
    projectId: 'chat-app-49d7a',
    storageBucket: 'chat-app-49d7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh4ihXuhnn-1PQwuRBJRbhA5_yWxU3qCE',
    appId: '1:829048536709:ios:d165192cc805d2d19833ec',
    messagingSenderId: '829048536709',
    projectId: 'chat-app-49d7a',
    storageBucket: 'chat-app-49d7a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh4ihXuhnn-1PQwuRBJRbhA5_yWxU3qCE',
    appId: '1:829048536709:ios:d165192cc805d2d19833ec',
    messagingSenderId: '829048536709',
    projectId: 'chat-app-49d7a',
    storageBucket: 'chat-app-49d7a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnsdma7ZbbPRwtrPxHTSAteDQTPvF8gQc',
    appId: '1:829048536709:web:e3246e6a215f57569833ec',
    messagingSenderId: '829048536709',
    projectId: 'chat-app-49d7a',
    authDomain: 'chat-app-49d7a.firebaseapp.com',
    storageBucket: 'chat-app-49d7a.firebasestorage.app',
    measurementId: 'G-KT1765TPTK',
  );
}
